### ISSUE TITLE
Deploy digital_business_card to a website

### ISSUE THREAD

**Issue by balinskia** [nngrz/React-project-set#3]
Follow https://youtu.be/7wzuievFjrk?si=K96ORi9RmlE1BhXx

**Acceptance criteria**
1. You can go to a website and see your business card on Github Pages
2. Add to your Digital card a short summary of your skills.
3. Add Portfolio Section - add there links to your Notes App and a link to the source code.

**Comment by balinskia** [comment]
@nngrz what is the url of your website?

**Comment by nngrz** [comment]
https://melodic-entremet-263e7b.netlify.app/

**Comment by nngrz** [comment]
> @nngrz what is the url of your website?

https://melodic-entremet-263e7b.netlify.app/

**Comment by balinskia** [comment]
I remember we deployed it to github pages, could you please find that url?

**Comment by nngrz** [comment]
> I remember we deployed it to github pages, could you please find that url?

this: https://nngrz.github.io/business-card/

**Comment by balinskia** [comment]
See my first comment, you can start working on this issue

**Comment by nngrz** [comment]
> See my first comment, you can start working on this issue
ok, once I finalize the notes_app
